### ISSUE TITLE
Fix 500 internal server error on About Page

### ISSUE THREAD

**Issue by gregboyer** [sfbrigade/codeforsanfrancisco.org#20]
The About page has a section displaying "500 Internal Server Error" 

https://codeforsanfrancisco.org/about/

**Comment by jszwedko** [comment]
@gregboyer do you still see this? I looked at the page just now, but couldn't find any errors. My best guess is that Youtube was returning a 500 as there was a Youtube outage yesterday.

**Comment by ProLoser** [comment]
This seems to be working fine so closing for now.
