### ISSUE TITLE
Integrate github repo to auto-publish to live website

### ISSUE THREAD

**Issue by ProLoser** [sfbrigade/codeforsanfrancisco.org#22]

**Comment by jszwedko** [comment]
This actually happens right now, but configured outside of the repo. The website is hosted on [Netlify](https://www.netlify.com/) which automatically deploys the master branch. In hindsight, this should have been documented :fearful: 

Current site administrators are myself, @jasonlally, and hello@codeforsanfrancisco.org. I'm more than happy to add further ones.

**Comment by ProLoser** [comment]
Cool, I'll dig around and document it. I'm surprised there's no hooks or integrations listed in this repositories settings

**Comment by jszwedko** [comment]
:+1: thanks for that.

The integration is via webhook, you can see it over here: https://github.com/sfbrigade/codeforsanfrancisco.org/settings/hooks

**Comment by ProLoser** [comment]
@jszwedko is the lastpass login information for netlify correct? I'm trying to login with it and it's not working.

**Comment by jszwedko** [comment]
Hmm, it was at one point. I generally only logged in with my user account though. You should be able to reset the password for hello@codeforsanfrancisco.org if it isn't working.

Let me know if you still have troubles with it!

**Comment by ProLoser** [comment]
Okay I went ahead and changed it back to what's currently stored in lastpass
