### ISSUE TITLE
Update "team" page

### ISSUE THREAD

**Issue by gregboyer** [sfbrigade/codeforsanfrancisco.org#30]
Update the "team" page here: https://codeforsanfrancisco.org/about/team/

**Comment by ProLoser** [comment]
Editing [this document](https://github.com/sfbrigade/codeforsanfrancisco.org/blob/master/_data/team.yml) should automatically update the team page. I don't know all the members however.

**Comment by emily-wasserman** [comment]
Marking closed, we have new roles up.
