### ISSUE TITLE
Date of next event not accurate on codeforsanfrancisco.org

### ISSUE THREAD

**Issue by gregboyer** [sfbrigade/codeforsanfrancisco.org#59]
The date of the next event is listed as 12-12, but today is 12-17. Does not appear to be an issue with the event markdown files.

**Comment by emily-wasserman** [comment]
There's a typo in the end time of the event, and the index page uses that time to determine what to show, apparently.

**Comment by emily-wasserman** [comment]
@gregboyer I can fix it myself

**Comment by gregboyer** [comment]
I had a few minutes at the airport and fixed it. Thanks for spotting that @emily-wasserman
