### ISSUE TITLE
Change link in meetup post from alpha to live site

### ISSUE THREAD

**Issue by jasonlally** [sfbrigade/codeforsanfrancisco.org#8]
https://github.com/sfbrigade/codeforsanfrancisco.org/blob/10bb8ea5c0bcd89fb06b925cbba6e5cf925b58fd/scripts/update-meetup#L66

@jszwedko - this link needs to be changed, but if we change this here, will it update past events too?

**Comment by jszwedko** [comment]
Thanks for catching this! I updated it and regenerated the event with the incorrect link.
